name: Health Management App CI/CD

on:
  push:
    branches:
      - develop
      - 'feature/**'
      - main
  pull_request:
    branches:
      - develop
      - 'feature/**'

jobs:
  test:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Run Tests on Develop/Feature Branches

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test ./... -v

  docker-build-and-push:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Build and Push Docker Image on Main

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/health-app:latest .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/health-app:latest 
